Fixed compilation error: functions do not overload
Added a virtual function signature to the base class (PicoGraphicsDV) for overridden methods since the compiler threw an error saying neither method was actually overloading anything and no matching definition was found in PicoGraphics class.